name: SHANE MORAND
favicon: null
layout_spectrum: 0.579387171426788
typography_spectrum: 0.371667007682845
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.15900175413116813
  lightness: 0.8106275429017842
  saturation: 0.57947410014458
  rhythmicContrast: 0.026970062870532274
purpose: []
